travis:
  secure:
    BINSTAR_TOKEN: zqgrZUNHEF+dYJGDVUqcblnV2xGHJ6lL/aMRB8P18DrX7I7o510YA/CACYqG52sZrBDwnTzq9IOTtPy8l5gklCfQFdb9zHVnpmwavpr10R4klnk9d9+AQ2wQ7UmpgzeAz9OuBregecf/xqUA+9W0oXeD4TUoIxKWi4aBC7g2l6t5l76JlhRJjqUcB5TGsyP3eqDs8qpxIsYy6PT3NS8R3AN/SAjgaugwaFDlUUvgbn1JeoIvw0cQRYBN3xTBec8ApEoHEcVVwdHww0sfDnfSLiBZNAapOm0f9450FIxOwQD/RUha/cLDMY8j5pSIWL5yinQCKmyIfizvkHPeJ2GtsxZga7S16FAz7WBU0A5gTVoSF5K9gqAQ1GVC1i6lb91C1HUZnzcjQRuqHs/OswS71il+pGuicWRgUolkyxP7Dhm9D2ypMPHMa9Pric/LRotZePonTjNKnYnrYY659u75dmaEcY5L/osbZrU4IhjuoLfWgBpbBEUnzosQ65Oj9de7WNkqM1KCzi8bfIbIZpP7wTNgKD36CfSpaZCH0Q3j/vVCUjTSyxQOUDmwhkohOc2t42Z2ROSCNKWoXvMkgLkxtmtrgkavX6wpqnJQIVggIVJHyr+yxFsJYVKwBiTkGEnZW6OyOgBk2g3OZAynESW7B12B726MN+LtorZqm1uwIGo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
